#!/usr/bin/env node
// Generated by LiveScript 1.3.1
(function(){
  var docopt, fs, doc, getOption, o, number, dry, language, directory;
  docopt = require('docopt').docopt;
  fs = require('fs');
  doc = "Usage:\n        apparmor-run gen-profiles [-d | --dry] [-n N] -l LANGUAGE -t DIRECTORY \n        apparmor-run -h | --help \n\nOptions:\n        -n, --number N                  Number of profiles to generate (defaults to 1)\n        -l, --language LANGUAGE         Use a specific language profile (currently `C` or `Matlab`)\n        -t, --target DIRECTORY          Generate profiles for DIRECTORY/LANGUAGE/ID/main";
  getOption = function(a, b, def, o){
    if (!o[a] && !o[b]) {
      return def;
    } else {
      return o[b];
    }
  };
  o = docopt(doc);
  number = getOption('-n', '--number', 1, o);
  dry = o['-d'] || o['--dry'];
  language = getOption('-l', '--language', null, o);
  directory = getOption('-t', '--target', null, o);
  console.log(o);
}).call(this);
